---
- name: Build and Push Docker Image to Docker Hub
  hosts: localhost
  vars:
    docker_image_name: "wadii10/mcq-front"
    docker_image_tag: "latest"
    docker_context_path: "./mcq-lab"
    dockerfile_path: "./mcq-lab/Dockerfile"
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

    - name: Build the Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build
        build:
          path: "{{ docker_context_path }}"
          dockerfile: "{{ dockerfile_path }}"

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: local
        push: yes