---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  vars:
    docker_image_name: "wadii10/mcq-front"
    docker_image_tag: "latest"
    dockerfile_path: "mcq-lab/Dockerfile"
    docker_context_path: "."
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

    - name: Build the Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        path: "{{ docker_context_path }}"
        dockerfile: "{{ dockerfile_path }}"
        force: true

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        push: true
- name: Deploy Kubernetes resources
  hosts: all
  collections:
    - kubernetes.core
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Apply create-namespace.yaml
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kube/create-namespace.yaml') }}"

    - name: Apply -f back.yaml
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kube/back.yaml') }}"

    
    - name: Apply -f front.yaml
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kube/front.yaml') }}"