version: '3.5'

services:
  front:
    build: ./mcq-lab
    container_name: wadii10/mcq-front:latest
    ports:
      - '4200:4200'
    volumes:
      - ./:/angular-app
    environment:
      - STYLE=css
  
  back:
    build: ./backend
    container_name: wadii10/mcq-back:latest
    ports:
      - "3000:3000"
    hostname: back
    command: npm start