version: '3.5'

services:
  front:
    build: ./mcq-lab
    container_name: front
    ports:
      - '4200:4200'
    volumes:
      - ./:/angular-app
    environment:
      - STYLE=css
  
  back:
    build: ./backend
    container_name: back
    ports:
      - "3000:3000"
    hostname: backendhost
    command: npm start