---
- name: Deploy Kubernetes resources
  hosts: all
  become: true
  collections:
    - kubernetes.core
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create namespace from create-namespace.yaml
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'kube/create-namespace.yaml') }}"

    - name: Apply configuration from back.yaml
      kubernetes.core.k8s:
        state: present  
        definition: "{{ lookup('file', 'kube/back.yaml') }}"

    - name: Apply configuration from front.yaml
      kubernetes.core.k8s:
        state: restarted
        definition: "{{ lookup('file', 'kube/front.yaml') }}"