apiVersion: v1
kind: ConfigMap
metadata:
  name: front-cm0
  labels:
    app: front
data:
  docker-compose.yml: "version: '3.5'\n\nservices:\n  front:\n    build: ./mcq-lab\n    container_name: wadii10/mcq-front:latest\n    ports:\n      - '4200:4200'\n    volumes:\n      - ./:/angular-app\n    environment:\n      - STYLE=css\n  \n  back:\n    build: ./backend\n    container_name: wadii10/mcq-back:latest\n    ports:\n      - \"3000:3000\"\n    hostname: back\n    command: npm start"
